#!/bin/env bash
config_path=$HOME/Dropbox/index/my-document-index-config

# Load configs
if [ -f $config_path ]; then
  source $config_path
else
  echo Config file $config_path does not exist
  exit 1
fi

if [[ $1 == "show_all" ]]; then
  # Show all possible inputs as one string
  echo "${!name_to_path[@]}"
else
  path=${name_to_path[$1]}
  extention="${path##*.}"  # extract path extention
  application=${extention_to_program[$extention]}
  echo Opening $path
  echo test
  if [ $# -gt 1 ] ; then
      application=$2
      echo "Use provided application ($application)"
      if command -v "$application" >/dev/null 2>&1 ; then
        $application "$path" &
      else
        echo Could not find application.
        echo Trying standard application
        xdg-open "$path"
      fi
  elif [ "$application" ] ; then
    echo Using application $application
    if command -v "$application" >/dev/null 2>&1 ; then
      $application "$path" &
    else
      echo Could not find application.
      echo Trying standard application
      xdg-open "$path"
    fi
  else
    echo No application specified
    echo Trying standard application
    xdg-open "$path"
  fi
fi
